---
- hosts: localhost
  become: yes
  become_user: root
  vars:
    ansible_python_interpreter: /usr/bin/python3
    local_username: user
    git_username: radtkedev
    git_email: mail@radtke.dev
    git_default_branch: master 
  tasks:
    - name: Reduce GRUB timeout
      register: grub_timeout
      lineinfile:
        path: /etc/default/grub
        regexp: "^GRUB_TIMEOUT="
        line: "GRUB_TIMEOUT=1"

    - name: Silence GRUB boot
      register: grub_cmdline
      lineinfile:
        path: /etc/default/grub
        regexp: "^GRUB_CMDLINE_LINUX="
        line: "GRUB_CMDLINE_LINUX=\"quiet rd.plymouth=0 plymouth.enable=0 loglevel=3\""

    - name: Update GRUB
      when: grub_timeout.changed or grub_cmdline.changed
      shell: "grub2-mkconfig -o /boot/efi/EFI/fedora/grub.cfg"

    - name: Set console font and keymap
      ansible.builtin.copy:
        dest: /etc/vconsole.conf
        content: |
          KEYMAP="de"
          FONT="ter-i16n"

    - name: Configure chrony NTP
      register: chrony
      ansible.builtin.copy:
        dest: /etc/chrony.conf
        content: |
          pool time.cloudflare.com iburst nts
          driftfile /var/lib/chrony/drift
          makestep 1.0 3
          rtcsync
          keyfile /etc/chrony.keys
          ntsdumpdir /var/lib/chrony
          leapsectz right/UTC
          logdir /var/log/chrony

    - name: Restart chrony
      when: chrony.changed
      ansible.builtin.service:
        name: chronyd
        state: restarted

    - name: Set up autologin (1/2)
      ansible.builtin.file:
        name: /etc/systemd/system/getty@tty1.service.d
        state: directory

    - name: Set up autologin (2/2)
      ansible.builtin.copy:
        dest: /etc/systemd/system/getty@tty1.service.d/override.conf
        content: |
          [Service]
          ExecStart=
          ExecStart=-/sbin/agetty --skip-login --nonewline --noissue --autologin {{ local_username }} --noclear %I $TERM

    - name: Remove last login information
      become_user: "{{ local_username }}"
      ansible.builtin.copy:
        content: ""
        dest: "/home/{{ local_username }}/.hushlogin"

    - name: Configure dnf
      ansible.builtin.copy:
        dest: /etc/dnf.conf
        content: |
          [main]
          gpgcheck=1
          installonly_limit=3
          clean_requirements_on_remove=True
          best=False
          skip_if_unavailable=True
          max_parallel_downloads=10
          deltarpm=true

    - name: Import RPM Fusion Free key
      rpm_key:
        state: present
        key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-2020

    - name: Enable RPM Fusion Free repository
      dnf:
        name: "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
        state: present

    - name: Update all packages
      dnf:
        name: "*"
        state: latest
        update_cache: true

    - name: Install system utilities
      dnf:
        name: 
          - htop
          - ImageMagick
          - zip
          - net-tools
          - bind-utils
          - pwgen
          - qrencode 
          - traceroute
          - whois
          - neovim
          - terminus-fonts
          - terminus-fonts-console
          - liberation-fonts
          - mesa-dri-drivers
        state: present

    - name: Install desktop applications
      dnf:
        name:
          - chromium
          - mpv
          - remmina
        state: present

    - name: Install desktop environment
      dnf:
        name:
          - i3
          - i3blocks
          - xorg-x11-server-Xorg
          - xorg-x11-xinit
          - freetype-freeworld
          - xinput
          - xkill
          - xsel
          - xrdb
          - xclip
          - xprop
          - setxkbmap
          - dmenu
          - picom
          - maim
          - gxkb
          - dbus-x11
          - dunst
          - keychain
          - nautilus
          - arc-theme
        state: present

    - name: Enable font configurations (1/3) 
      file:
        src: /usr/share/fontconfig/conf.avail/10-autohint.conf
        dest: /etc/fonts/conf.d/10-autohint.conf
        state: link

    - name: Enable font configurations (2/3) 
      file:
        src: /usr/share/fontconfig/conf.avail/10-sub-pixel-rgb.conf
        dest: /etc/fonts/conf.d/10-sub-pixel-rgb.conf
        state: link

    - name: Enable font configurations (3/3) 
      file:
        src: /usr/share/fontconfig/conf.avail/11-lcdfilter-default.conf
        dest: /etc/fonts/conf.d/11-lcdfilter-default.conf
        state: link

    - name: Enable font antialiasing in dconf (1/2)
      ansible.builtin.command: gsettings set org.gnome.desktop.interface font-antialiasing "rgba"

    - name: Enable font antialiasing in dconf (2/2)
      ansible.builtin.command: gsettings set org.gnome.desktop.interface font-hinting "slight"

    - name: Install media tools
      dnf:
        name:
          - volumeicon
          - alsa-utils
          - playerctl
          - ffmpeg
          - "@Multimedia"
        exclude:
          - pipewire-pulseaudio
          - pipewire-alsa
          - pipewire-utils
          - wireplumber
        state: present

    - name: Remove pipewire
      dnf:
        name:
          - pipewire
          - pipewire-pulseaudio
          - pipewire-alsa
          - wireplumber
        state: absent
        autoremove: yes

    - name: Install disk and networking utilities
      dnf:
        name:
          - NetworkManager
          - NetworkManager-openconnect
          - NetworkManager-openconnect-gnome
          - udiskie
        state: present

    - name: Check if ncspot is available
      register: ncspot
      stat:
        path: /usr/local/bin/ncspot

    - name: Install ncspot dependencies
      when: not ncspot.stat.exists
      dnf:
        name:
          - cargo
          - alsa-lib-devel
          - libxcb-devel
          - openssl-devel
          - ncurses-devel
          - dbus-devel
        state: present

    - name: Create ncspot build directory
      when: not ncspot.stat.exists
      ansible.builtin.file:
        path: /tmp/ncspot
        state: directory

    - name: Pull ncspot repository
      when: not ncspot.stat.exists
      ansible.builtin.unarchive:
        src: https://api.github.com/repos/hrkfdn/ncspot/tarball
        dest: /tmp/ncspot
        remote_src: yes
        extra_opts: [--strip-components=1]

    - name: Compile ncspot with alsa-backend
      when: not ncspot.stat.exists
      ansible.builtin.command: cargo build --manifest-path /tmp/ncspot/Cargo.toml --release --no-default-features --features share_clipboard,alsa_backend,mpris,notify,cursive/pancurses-backend

    - name: Copy ncspot binary to /usr/local/bin
      when: not ncspot.stat.exists
      ansible.builtin.copy:
        src: /tmp/ncspot/target/release/ncspot
        dest: /usr/local/bin/ncspot
        mode: 755

    - name: Remove ncspot build directory
      when: not ncspot.stat.exists
      ansible.builtin.file:
        path: /tmp/ncspot
        state: absent

    - name: Setup client ssh folder
      become_user: "{{ local_username }}"
      ansible.builtin.file:
        path: "/home/{{ local_username }}/.ssh"
        state: directory
        mode: 0700

    - name: Configure ssh
      become_user: "{{ local_username }}"
      ansible.builtin.copy:
        dest: /home/{{ local_username }}/.ssh/config
        content: |
          User root
          AddKeysToAgent yes

    - name: Setup configuration directories
      become_user: "{{ local_username }}"
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      loop:
        - /home/{{ local_username }}/.config/i3
        - /home/{{ local_username }}/.config/i3blocks
        - /home/{{ local_username }}/.config/dunst
        - /home/{{ local_username }}/.config/remmina
        - /home/{{ local_username }}/.config/gtk-3.0
        - /home/{{ local_username }}/.config/gtk-4.0
        - /home/{{ local_username }}/.config/nvim
        - /home/{{ local_username }}/.local/share/nvim/site/autoload

    - name: Download vim-plug
      become_user: "{{ local_username }}"
      get_url:
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: /home/{{ local_username }}/.local/share/nvim/site/autoload/plug.vim

    - name: Set up init.vim
      become_user: "{{ local_username }}"
      ansible.builtin.copy:
        src: .config/nvim/init.vim
        dest: /home/{{ local_username }}/.bashrc

    - name: Set git username
      become_user: "{{ local_username }}"
      git_config:
        name: user.name
        value: "{{ git_username }}"
        scope: global

    - name: Set git email
      become_user: "{{ local_username }}"
      git_config:
        name: user.email
        value: "{{ git_email }}"
        scope: global

    - name: Setup git default branch
      become_user: "{{ local_username }}"
      git_config:
        name: init.defaultBranch
        value: "{{ git_default_branch }}"
        scope: global

    - name: Set up .bashrc
      become_user: "{{ local_username }}"
      ansible.builtin.copy:
        src: .bashrc
        dest: /home/{{ local_username }}/.bashrc

    - name: Set up .bash_profile
      become_user: "{{ local_username }}"
      ansible.builtin.copy:
        src: .bash_profile
        dest: /home/{{ local_username }}/.bash_profile

    - name: Set up .xinitrc
      become_user: "{{ local_username }}"
      ansible.builtin.copy:
        src: .xinitrc
        dest: /home/{{ local_username }}/.xinitrc

    - name: Set up .Xresources
      become_user: "{{ local_username }}"
      ansible.builtin.copy:
        src: .Xresources
        dest: /home/{{ local_username }}/.Xresources

    - name: Set up i3 config
      become_user: "{{ local_username }}"
      ansible.builtin.copy:
        src: .config/i3/config
        dest: /home/{{ local_username }}/.config/i3/config

    - name: Set up i3blocks config
      become_user: "{{ local_username }}"
      ansible.builtin.copy:
        src: .config/i3blocks/config
        dest: /home/{{ local_username }}/.config/i3blocks/config

    - name: Set up dunst config
      become_user: "{{ local_username }}"
      ansible.builtin.copy:
        src: .config/dunst/dunstrc
        dest: /home/{{ local_username }}/.config/dunst/dunstrc

    - name: Set up remmina config
      become_user: "{{ local_username }}"
      ansible.builtin.copy:
        src: .config/remmina/remmina.pref
        dest: /home/{{ local_username }}/.config/remmina/remmina.pref

    - name: Set up gtk-3.0
      become_user: "{{ local_username }}"
      ansible.builtin.copy:
        src: .config/gtk-3.0/settings.ini
        dest: /home/{{ local_username }}/.config/gtk-3.0/settings.ini

    - name: Set up gtk-4.0
      become_user: "{{ local_username }}"
      ansible.builtin.copy:
        src: .config/gtk-4.0/settings.ini
        dest: /home/{{ local_username }}/.config/gtk-4.0/settings.ini

    - name: Set up neovim
      become_user: "{{ local_username }}"
      ansible.builtin.copy:
        src: .config/nvim/init.vim
        dest: /home/{{ local_username }}/.config/nvim/init.vim

    - name: Install neovim plugins
      become_user: "{{ local_username }}"
      ansible.builtin.command: nvim +PlugInstall +qall

